#!/bin/bash

# Copyright 2021 Mattias Bengtsson <mattias.jc.bengtsson@gmail.com>
# SPDX-License-Identifier: GPL-3.0-or-later

function error-message {
    cat << EOM
ioquake3 needs the official Quake 3 .pk3-files to function
properly (specifically baseq3/pak0.pk3 … baseq3/pak8.pk3 and
optionally also missionpack/pak0.pk3 … missionpack/pak3.pk3).

One way to obtain these files is to buy Quake 3 Arena on
Steam, and extract the files from the installation directory.

You may also need latest point release pk3 files. These can be
downloaded from here:

    https://ioquake3.org/extras/patch-data/

Once you've obtained all the required files, copy them to:

    ~/.var/app/org.ioquake3.IOQuake3/.q3a/

… and restart ioquake3
EOM
}

# Ensure ioquake3 reaches our pak-files and configs.
mkdir -p "${HOME}"/.q3a/{baseq3,missionpack}

for i in $(seq 0 8); do
    if [ ! -f "${HOME}/.q3a/baseq3/pak${i}.pk3" ]; then
        zenity --error      \
               --width=400  \
               --height=200 \
               --text="$(error-message)"
        exit 2
    fi
done

/app/share/ioquake3/ioquake3.* "$@"
